get_tweets_by_id:
  bearer_token: None
  consumer_key: None
  consumer_secret: None
  endpoint: https://api.twitter.com/2/tweets/
search_tweets:
  bearer_token: None
  consumer_key: None
  consumer_secret: None
  endpoint: https://api.twitter.com/2/tweets/search/recent
user_mention:
  bearer_token: None
  consumer_key: None
  consumer_secret: None
  endpoint: https://api.twitter.com/2/users/:id/mentions
user_tweets:
  bearer_token: None
  consumer_key: None
  consumer_secret: None
  endpoint: https://api.twitter.com/2/users/:id/tweet
