---
# file: playbook.yml
- hosts: dev # deploy_pp #
  become_method: sudo
  vars:
    project_dir: /home/{{ wdrax_user }}/wdra-extender
    wdrax_user: wdrax
    LOG_LEVEL: DEBUG  # Passed to web server via docker-compose.yml
    db_host: db

  pre_tasks:
    - name: Install Ansible prerequisites
      dnf:
        name: '{{ packages }}'
        state: latest
        update_cache: yes
      vars:
        packages:
          - python3
          - python3-setuptools
          - python3-pip
          - libselinux-python3
          - yum-utils
          - git
          - https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
      become_user: root
      become: yes
  roles:
    - docker
    - wdrax
