---
- hosts: all
  become_method: sudo

  pre_tasks:
    - name: Install Ansible prerequisites
      yum:
        name: '{{ packages }}'
        state: latest
        update_cache: yes
      vars:
        packages:
          - python
          - python3
          - python3-setuptools
          - python3-pip
          - libselinux-python3
      become_user: root
      become: yes

  roles:
    - docker

  tasks:
    - name: Switch to Python3 interpreter for following tasks
      set_fact:
        ansible_python_interpreter: python3

    - name: Create WDRAX user
      user:
        name: '{{ wdrax_user }}'
        groups:
          - docker
        append: yes
      become_user: root
      become: yes

    - block:
      - name: Clone / update from source repo
        git:
          repo: 'https://github.com/Southampton-RSG/wdra-extender.git'
          dest: '{{ project_dir }}'
          version: '{{ git_branch | default ("master") }}'
          accept_hostkey: yes

      - name: Install docker-compose
        pip:
          name:
            - docker
            - docker-compose
          state: latest
          extra_args: --user

      - name: Fetch remote docker-compose template
        fetch:
          src: '{{ project_dir }}/docker-compose.yml.j2'
          dest: /tmp
        register: compose_template

      - name: Populate docker-compose template
        template:
          src: '{{ compose_template.dest }}'
          dest: '{{ project_dir }}/docker-compose.yml'

      - name: Touch database file
        file:
          path: '{{ project_dir }}/db.sqlite3'
          state: touch
          owner: '{{ wdrax_user }}'

      - name: Build Docker image
        docker_image:
          build:
            path: '{{ project_dir }}'
          source: build
          name: wdrax
          tag: dev

      - name: Perform DB migrations
        docker_container:
          name: migrate
          image: wdrax:dev
          command: python -m flask db upgrade
          state: started
          restart: yes
          volumes:
            - '{{ project_dir }}/db.sqlite3:/var/www/wdrax/db.sqlite3'

      - name: Run containers with docker-compose
        docker_compose:
          project_src: '{{ project_dir }}'

      become_user: '{{ wdrax_user }}'
      become: yes

  vars:
    ansible_python_interpreter: python2
    project_dir: /home/{{ wdrax_user }}/wdra-extender
    wdrax_user: wdrax
