---
# file: playbook.yml
- hosts: dev
  become_method: sudo

  vars:
    project_dir: /home/{{ wdrax_user }}/wdra-extender
    wdrax_user: wdrax
    deploy_type: dev
    LOG_LEVEL: DEBUG  # Passed to web server via docker-compose.yml

  pre_tasks:

    - name: Install Ansible prerequisites
      yum:
        name: '{{ packages }}'
        state: latest
        update_cache: yes
      vars:
        packages:
          - python3
          - python3-setuptools
          - python3-pip
          - libselinux-python3
          - yum-utils
      become_user: root
      become: yes

  roles:
    - docker
    - wdrax
