"""empty message

Revision ID: 1186d778c776
Revises: 370a1a9bfdaf
Create Date: 2021-02-12 12:29:21.616757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1186d778c776'
down_revision = '370a1a9bfdaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('barer_token', sa.String(), nullable=True))
    op.add_column('user', sa.Column('consumer_key', sa.String(), nullable=True))
    op.add_column('user', sa.Column('consumer_secret', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'consumer_secret')
    op.drop_column('user', 'consumer_key')
    op.drop_column('user', 'barer_token')
    # ### end Alembic commands ###
