"""empty message

Revision ID: 254eecd02877
Revises: 49d605b8ad04
Create Date: 2021-03-18 17:33:30.090318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '254eecd02877'
down_revision = '49d605b8ad04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wdrax_users', sa.Column('endpoints', sa.PickleType(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wdrax_users', 'endpoints')
    # ### end Alembic commands ###
