"""empty message

Revision ID: 49d605b8ad04
Revises: bd448abce7bf
Create Date: 2021-03-15 12:08:52.804881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49d605b8ad04'
down_revision = 'bd448abce7bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'wdrax_users', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wdrax_users', type_='unique')
    # ### end Alembic commands ###
