"""Initial migration

Revision ID: 85c9684904bf
Revises: 
Create Date: 2020-05-11 16:41:35.221257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85c9684904bf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extract',
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_extract_email'), 'extract', ['email'], unique=False)
    op.create_index(op.f('ix_extract_uuid'), 'extract', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_extract_uuid'), table_name='extract')
    op.drop_index(op.f('ix_extract_email'), table_name='extract')
    op.drop_table('extract')
    # ### end Alembic commands ###
