"""empty message

Revision ID: 88db6132617a
Revises: 8f4032f0a5ab
Create Date: 2021-02-18 14:55:13.534123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88db6132617a'
down_revision = '8f4032f0a5ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('bearer_token', sa.String(), nullable=True))
    op.drop_column('user', 'barer_token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('barer_token', sa.VARCHAR(), nullable=True))
    op.drop_column('user', 'bearer_token')
    # ### end Alembic commands ###
