"""empty message

Revision ID: 8f4032f0a5ab
Revises: 1186d778c776
Create Date: 2021-02-12 15:07:58.554766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f4032f0a5ab'
down_revision = '1186d778c776'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('access_token', sa.String(), nullable=True))
    op.add_column('user', sa.Column('access_token_secret', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'access_token_secret')
    op.drop_column('user', 'access_token')
    # ### end Alembic commands ###
