"""empty message

Revision ID: 986e6e375d70
Revises: 
Create Date: 2021-02-11 16:31:32.767869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '986e6e375d70'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extract',
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Unicode(length=16), nullable=True),
    sa.Column('validate_on_email', sa.Boolean(), nullable=True),
    sa.Column('ready', sa.Boolean(), nullable=False),
    sa.Column('extract_method', sa.String(length=254), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_extract_ready'), 'extract', ['ready'], unique=False)
    op.create_index(op.f('ix_extract_user_id'), 'extract', ['user_id'], unique=False)
    op.create_index(op.f('ix_extract_uuid'), 'extract', ['uuid'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=1000), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_index(op.f('ix_extract_uuid'), table_name='extract')
    op.drop_index(op.f('ix_extract_user_id'), table_name='extract')
    op.drop_index(op.f('ix_extract_ready'), table_name='extract')
    op.drop_table('extract')
    # ### end Alembic commands ###
