"""empty message

Revision ID: 9bc1b51d5959
Revises: fd5e6804fad3
Create Date: 2021-02-11 12:55:02.795827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bc1b51d5959'
down_revision = 'fd5e6804fad3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('extract', 'email')
    op.add_column('user', sa.Column('email', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('name', sa.String(length=1000), nullable=True))
    op.drop_index('ix_user_id', table_name='user')
    op.drop_index('ix_user_user_email', table_name='user')
    op.create_unique_constraint(None, 'user', ['email'])
    op.drop_column('user', 'user_email')
    op.drop_column('user', 'id_set')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('id_set', sa.BOOLEAN(), nullable=True))
    op.add_column('user', sa.Column('user_email', sa.VARCHAR(length=254), nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index('ix_user_user_email', 'user', ['user_email'], unique=1)
    op.create_index('ix_user_id', 'user', ['id'], unique=1)
    op.drop_column('user', 'name')
    op.drop_column('user', 'email')
    op.add_column('extract', sa.Column('email', sa.VARCHAR(length=254), nullable=False))
    # ### end Alembic commands ###
