"""empty message

Revision ID: bd448abce7bf
Revises: 
Create Date: 2021-03-12 14:22:29.933036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd448abce7bf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wdrax_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=1000), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('twitter_keys_set', sa.Boolean(), nullable=True),
    sa.Column('bearer_token', sa.String(), nullable=True),
    sa.Column('consumer_key', sa.String(), nullable=True),
    sa.Column('consumer_secret', sa.String(), nullable=True),
    sa.Column('access_token', sa.String(), nullable=True),
    sa.Column('access_token_secret', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('extracts',
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('validate_on_email', sa.Boolean(), nullable=True),
    sa.Column('ready', sa.Boolean(), nullable=False),
    sa.Column('building', sa.Boolean(), nullable=True),
    sa.Column('extract_method', sa.String(length=254), nullable=False),
    sa.Column('query_string', sa.String(length=1024), nullable=True),
    sa.Column('search_settings', sa.PickleType(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['wdrax_users.id'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_extracts_ready'), 'extracts', ['ready'], unique=False)
    op.create_index(op.f('ix_extracts_user_id'), 'extracts', ['user_id'], unique=False)
    op.create_index(op.f('ix_extracts_uuid'), 'extracts', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_extracts_uuid'), table_name='extracts')
    op.drop_index(op.f('ix_extracts_user_id'), table_name='extracts')
    op.drop_index(op.f('ix_extracts_ready'), table_name='extracts')
    op.drop_table('extracts')
    op.drop_table('wdrax_users')
    # ### end Alembic commands ###
