"""empty message

Revision ID: cb01108cd002
Revises: 
Create Date: 2021-03-10 10:45:45.286266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb01108cd002'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extract',
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('validate_on_email', sa.Boolean(), nullable=True),
    sa.Column('ready', sa.Boolean(), nullable=False),
    sa.Column('building', sa.Boolean(), nullable=True),
    sa.Column('extract_method', sa.String(length=254), nullable=False),
    sa.Column('query_string', sa.String(length=1024), nullable=True),
    sa.Column('search_settings', sa.PickleType(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_extract_ready'), 'extract', ['ready'], unique=False)
    op.create_index(op.f('ix_extract_user_id'), 'extract', ['user_id'], unique=False)
    op.create_index(op.f('ix_extract_uuid'), 'extract', ['uuid'], unique=True)
    op.create_table('wdrax_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=1000), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('twitter_keys_set', sa.Boolean(), nullable=True),
    sa.Column('bearer_token', sa.String(), nullable=True),
    sa.Column('consumer_key', sa.String(), nullable=True),
    sa.Column('consumer_secret', sa.String(), nullable=True),
    sa.Column('access_token', sa.String(), nullable=True),
    sa.Column('access_token_secret', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id')
    )
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('twitter_keys_set', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('bearer_token', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('consumer_key', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('consumer_secret', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('access_token', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('access_token_secret', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('email', name='user_email_key')
    )
    op.drop_table('wdrax_user')
    op.drop_index(op.f('ix_extract_uuid'), table_name='extract')
    op.drop_index(op.f('ix_extract_user_id'), table_name='extract')
    op.drop_index(op.f('ix_extract_ready'), table_name='extract')
    op.drop_table('extract')
    # ### end Alembic commands ###
