"""Add Extract.ready

Revision ID: d652dee9505e
Revises: 85c9684904bf
Create Date: 2020-05-12 15:03:03.183133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd652dee9505e'
down_revision = '85c9684904bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extract', sa.Column('ready', sa.Boolean(), server_default='false', nullable=False))
    op.create_index(op.f('ix_extract_ready'), 'extract', ['ready'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_extract_ready'), table_name='extract')
    op.drop_column('extract', 'ready')
    # ### end Alembic commands ###
