"""addding extract method

Revision ID: fd5e6804fad3
Revises: d652dee9505e
Create Date: 2021-01-15 09:29:58.341044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd5e6804fad3'
down_revision = 'd652dee9505e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extract', sa.Column('extract_method', sa.String(length=254), nullable=False))
    op.create_index(op.f('ix_extract_extract_method'), 'extract', ['extract_method'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_extract_extract_method'), table_name='extract')
    op.drop_column('extract', 'extract_method')
    # ### end Alembic commands ###
