"""update extract for deleteing and rebuilding

Revision ID: fe171a17ccd5
Revises: 88db6132617a
Create Date: 2021-03-08 09:16:09.837683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe171a17ccd5'
down_revision = '88db6132617a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extract', sa.Column('building', sa.Boolean(), nullable=True))
    op.add_column('extract', sa.Column('query_string', sa.String(length=1024), nullable=True))
    op.add_column('extract', sa.Column('search_settings', sa.PickleType(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('extract', 'search_settings')
    op.drop_column('extract', 'query_string')
    op.drop_column('extract', 'building')
    # ### end Alembic commands ###
