---
# file: roles/wdrax/tasks/main.yml
- name: create user
  block:
    - name: Create WDRAX user
      user:
        name: '{{ wdrax_user }}'
        groups:
          - docker
        append: yes

    - name: Enable EPEL
      yum:
        name: epel-release
        state: latest

  become_user: root
  become: yes

- name: Clone repo and use docker to start app
  block:
    - name: Clone / update from source repo
      git:
        repo: 'https://github.com/Southampton-RSG/wdra-extender.git'
        dest: '{{ project_dir }}'
        version: '{{ git_branch | default ("dev") }}'
        accept_hostkey: yes

    - name: Install docker-compose
      pip:
        name:
          - docker
          - docker-compose
        state: latest
        extra_args: --user

    - name: Populate docker-compose template
      template:
        src: 'docker-compose.yml.j2'
        dest: '{{ project_dir }}/docker-compose.yml'
        force: yes

    - name: Build Docker image
      docker_image:
        build:
          path: '{{ project_dir }}'
          network: host
        name: wdrax
        tag: '{{ docker_tag }}'
        source: build

    - name: Run containers with docker-compose
      docker_compose:
        project_src: '{{ project_dir }}'
        state: present
        recreate: always

    - name: Add wdrax_container to inventory
      add_host:
        name: wdrax
        ansible_connection: docker
      changed_when: false

    - name: Make DB migrations
       delegate_to: wdrax
       command: flask db migrate

    - name: Perform DB migrations
      delegate_to: wdrax
      command: flask db upgrade

  become_user: '{{ wdrax_user }}'
  become: yes
