---
# file: roles/docker/tasks/main.yml
- block:
  - name: CentOS-8
    dnf:
      enablerepo: https://download.docker.com/linux/centos/docker-ce.repo
    when: vars.deploy_type == 0
  # RHEL-8
  - name: RHEL-8
    get_url:
      url: https://download.docker.com/linux/centos/docker-ce.repo
      dest: /etc/yum.repos.d/docker-ce.repo
    when: vars.deploy_type == 1

  - name: Install Docker
    dnf:
      name: '{{ packages }}'
      state: latest
      update_cache: yes
    vars:
      packages:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - git

  - name: Start Docker service
    systemd:
      name: docker
      state: started
      enabled: yes

  - name: Install docker-compose
    get_url:
      url: https://github.com/docker/compose/releases/download/1.28.4/docker-compose-Linux-x86_64
      dest: /usr/bin/docker-compose
      mode: a+x

  become_user: root
  become: yes
