---
# file: roles/docker/tasks/main.yml
- block:
  - name: CentOS-8
    get_url:
      url: https://download.docker.com/linux/centos/docker-ce.repo
      dest: /etc/yum.repos.d/docker-ce.repo
    when: "'dev' in inventory_hostname"
  # RHEL-8
  - name: RHEL-8
    get_url:
      url: https://download.docker.com/linux/rhel/docker-ce.repo
      dest: /etc/yum.repos.d/docker-ce.repo
    when: "'deploy_pp' in inventory_hostname"

  - name: Install Docker
    yum:
      name: '{{ packages }}'
      state: latest
      update_cache: yes
    vars:
      packages:
        - git
        - docker-ce
        - docker-ce-cli
        - containerd.io

  - name: Start Docker service
    systemd:
      name: docker
      state: started
      enabled: yes

  - name: Install docker-compose
    get_url:
      url: https://github.com/docker/compose/releases/download/1.27.4/docker-compose-Linux-x86_64
      dest: /usr/bin/docker-compose
      mode: a+x

  become_user: root
  become: yes
